### INDEX ###

DOCUMENT_LENGTH_KEYWORD = "LENGTH"
SPIMI_BLOCK_SIZE = 1000

### REGEX ###

AND_REGEX = "AND"
PHRASAL_REGEX = "\"(*)\""

### QUERY EXPANSION ###

EXPAND_NUM_OF_SYNONYMS = 2

### QUERY PSEUDO RELEVANCE FEEDBACK ###

PRF_NUM_OF_RESULTS = 5
PRF_NUM_OF_WORDS_PER_DOC = 1