### INDEX ###
DOCUMENT_LENGTH_KEYWORD = "LENGTH"
SPIMI_BLOCK_SIZE = 1000

### QUERY KEYWORD ###
AND_KEYWORD = "AND"
DOUBLE_QUOTE_KEYWORD = "\""
QUERY_KEYWORDS = [AND_KEYWORD, DOUBLE_QUOTE_KEYWORD]

### QUERY EXPANSION ###
EXPAND_NUM_OF_SYNONYMS = 2

### QUERY PSEUDO RELEVANCE FEEDBACK ###
PRF_NUM_OF_RESULTS = 5
PRF_NUM_OF_WORDS_PER_DOC = 1

### PHRASAL QUERIES ###
DOC_ID = 0 
TF = 1 
POS_LIST = 2